import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { ReportData } from '../types';

export async function generatePDF(reportData: ReportData): Promise<Buffer> {
  let browser = null;
  try {
    const isLocal = process.env.NODE_ENV !== 'production';
    

    const launchOptions: any = {
      headless: true,
    };
    
    if (isLocal) {
      // For local development, we fallback to standard Chrome paths for puppeteer-core
      launchOptions.executablePath = process.env.CHROME_EXECUTABLE_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    } else {
      launchOptions.args = chromium.args;
      launchOptions.defaultViewport = { width: 1200, height: 800 };
      launchOptions.executablePath = await chromium.executablePath();
      launchOptions.headless = true;
    }

    browser = await puppeteer.launch(launchOptions);

    const page = await browser.newPage();
    
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Report for ${reportData.company}</title>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 0; }
          .cover { height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); color: white; text-align: center; }
          .cover h1 { font-size: 48px; margin-bottom: 10px; }
          .cover p { font-size: 24px; opacity: 0.8; }
          .page { padding: 60px; page-break-after: always; }
          h2 { color: #2563eb; font-size: 32px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; }
          p, li { font-size: 16px; line-height: 1.6; color: #4b5563; margin-bottom: 15px; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
          .card h3 { margin-top: 0; color: #0f172a; }
          .footer { text-align: center; padding: 20px; font-size: 14px; color: #9ca3af; border-top: 1px solid #e5e7eb; }
        </style>
      </head>
      <body>
        <div class="cover">
          <h1>Growth & Audit Report</h1>
          <p>Prepared for <strong>${reportData.company}</strong></p>
          <p style="font-size: 16px; margin-top: 50px;">Generated by LeadForge AI</p>
        </div>
        
        <div class="page">
          <h2>Business Overview</h2>
          <div class="card">
            <h3>Identified Niche</h3>
            <p>${reportData.niche}</p>
          </div>
          <div class="card">
            <h3>Initial Insights</h3>
            <p>${reportData.insights.replace(/\\n/g, '<br/>')}</p>
          </div>
        </div>

        <div class="page">
          <h2>Technical & SEO Analysis</h2>
          <div class="card">
            <h3>SEO Recommendations</h3>
            <p>${reportData.seoRecommendations}</p>
          </div>
          <div class="card">
            <h3>Technical Recommendations</h3>
            <p>${reportData.technicalRecommendations}</p>
          </div>
        </div>

        <div class="page">
          <h2>Growth & Conversion Strategy</h2>
          <div class="card">
            <h3>UX & Design Suggestions</h3>
            <p>${reportData.uxSuggestions}</p>
          </div>
          <div class="card">
            <h3>Growth Opportunities</h3>
            <p>${reportData.growthOpportunities}</p>
          </div>
          <div class="card">
            <h3>Conversion Optimization</h3>
            <p>${reportData.conversionOptimization}</p>
          </div>
        </div>
        
        <div class="footer">
          &copy; ${new Date().getFullYear()} LeadForge AI. All rights reserved. | Confidential Report for ${reportData.company}
        </div>
      </body>
      </html>
    `;

    await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '0', right: '0', bottom: '0', left: '0' }
    });

    return Buffer.from(pdfBuffer);
  } catch (error) {
    console.error('PDF Generation failed:', error);
    throw error;
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}
